# Pandas:
   Python library for data analysis
# Pandas Data Structure 
    - Pandas Series 
    - Pandas DataFrame

#### Pandas Series:
      Data in 1D is series. 
      Data with Only Singlle Column

In [30]:
import pandas as pd

In [31]:
s1 = pd.Series(['Apples','Oranges','Mangoes','Cherries'])
s1

0      Apples
1     Oranges
2     Mangoes
3    Cherries
dtype: object

Components: 
    Values : we provoided values
    Index  : It uses default indices
    Dtype  : since all values are strings (objects)
    Name   : Name of the series

In [32]:
s1 = pd.Series(['Apples','Oranges','Mangoes','Cherries'], index=[12,24,12,36], name='fruits')
s1

12      Apples
24     Oranges
12     Mangoes
36    Cherries
Name: fruits, dtype: object

In [33]:
s2 = pd.Series(data=[12,24,12,36,24,12,48,60],index=['Apples','Oranges','Mangoes','Cherries','Bananas','Gauva','Lemon','Kiwi'])

In [34]:
# indices can be string indices
s2

Apples      12
Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
Lemon       48
Kiwi        60
dtype: int64

In [35]:
# Note: when providing string indices still we can refer to default inrt indices

In [36]:
s2['Lemon']

np.int64(48)

In [37]:
s2['Mangoes']

np.int64(12)

In [38]:
s1[24]

'Oranges'

In [39]:
# using default indices over string indices
s2

Apples      12
Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
Lemon       48
Kiwi        60
dtype: int64

In [40]:
s2.iloc[4]

np.int64(24)

In [41]:
s2.loc['Gauva']

np.int64(12)

# Slice a Series

In [42]:
s1

12      Apples
24     Oranges
12     Mangoes
36    Cherries
Name: fruits, dtype: object

In [43]:
s1.iloc[0:3] # int index dont include last index in slice

12     Apples
24    Oranges
12    Mangoes
Name: fruits, dtype: object

In [44]:
s2['Oranges':'Gauva'] # where string index include last one also.

Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
dtype: int64

# DataFrame:
   - Data with more than one columns.
   - 2D data

In [45]:
result = {'Roll':[11,12,13,14,15,16,17,18,19, 20],
          'Name':['Usman','Rehana','Ghaffar','Nawaz','Bilwal','Hashir', 'Maryam','Asim','Rehan','Sana'],
          'Python':[75,67,78,89,90,98,87,76,45,90],
          'Pandas':[87,78,98,91,61,73,94,85,78,90], 
          'Statistics':[89,67,89,76,78,56,54,56,78,98],
          'MachineLearning':[87,78,98,91,61,73,94,85,78,90],'DeepLearning':[75,67,78,89,90,98,87,76,45,90]}
result

{'Roll': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 'Name': ['Usman',
  'Rehana',
  'Ghaffar',
  'Nawaz',
  'Bilwal',
  'Hashir',
  'Maryam',
  'Asim',
  'Rehan',
  'Sana'],
 'Python': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90],
 'Pandas': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'Statistics': [89, 67, 89, 76, 78, 56, 54, 56, 78, 98],
 'MachineLearning': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'DeepLearning': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90]}

In [46]:
result = pd.DataFrame(result)
result

   Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90

#### Working with Columns
   - Adding more columns to df
       - passing hard coded value
       - generate data from data
                 
   - Del columns from df
   - Access single column (series)
   - Access multiple columns (2d)

In [47]:
result['Total']= result.Python + result.Pandas + result.MachineLearning + result.Statistics + result.DeepLearning
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total
0,11,Usman,75,87,89,87,75,413
1,12,Rehana,67,78,67,78,67,357
2,13,Ghaffar,78,98,89,98,78,441
3,14,Nawaz,89,91,76,91,89,436
4,15,Bilwal,90,61,78,61,90,380
5,16,Hashir,98,73,56,73,98,398
6,17,Maryam,87,94,54,94,87,416
7,18,Asim,76,85,56,85,76,378
8,19,Rehan,45,78,78,78,45,324
9,20,Sana,90,90,98,90,90,458

In [48]:
result['Percentage'] = result.Total/500*100
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage
0,11,Usman,75,87,89,87,75,413,82.6
1,12,Rehana,67,78,67,78,67,357,71.4
2,13,Ghaffar,78,98,89,98,78,441,88.2
3,14,Nawaz,89,91,76,91,89,436,87.2
4,15,Bilwal,90,61,78,61,90,380,76.0
5,16,Hashir,98,73,56,73,98,398,79.6
6,17,Maryam,87,94,54,94,87,416,83.2
7,18,Asim,76,85,56,85,76,378,75.6
8,19,Rehan,45,78,78,78,45,324,64.8
9,20,Sana,90,90,98,90,90,458,91.6

##### List Comprenshion

In [49]:
result['Grade3'] = ["A+" if per>=90 
                    else "A" if per>=80 
                    else "B" if per>=70 
                    else "C" if per>=60 
                    else "D" if per>=50 else "F"   
                                for per in result.Percentage]
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade3
0,11,Usman,75,87,89,87,75,413,82.6,A
1,12,Rehana,67,78,67,78,67,357,71.4,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B
5,16,Hashir,98,73,56,73,98,398,79.6,B
6,17,Maryam,87,94,54,94,87,416,83.2,A
7,18,Asim,76,85,56,85,76,378,75.6,B
8,19,Rehan,45,78,78,78,45,324,64.8,C
9,20,Sana,90,90,98,90,90,458,91.6,A+

#### lambda function are anonymous function / Inline Function

In [50]:
result['Grade4'] = result.Percentage.apply(lambda per:"A+" if per>=90 else "A" if per>=80 else "B" if per>=70 else "C" if per>=60 else "D" if per>=50 else"F")

In [51]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade3,Grade4
0,11,Usman,75,87,89,87,75,413,82.6,A,A
1,12,Rehana,67,78,67,78,67,357,71.4,B,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B,B
5,16,Hashir,98,73,56,73,98,398,79.6,B,B
6,17,Maryam,87,94,54,94,87,416,83.2,A,A
7,18,Asim,76,85,56,85,76,378,75.6,B,B
8,19,Rehan,45,78,78,78,45,324,64.8,C,C
9,20,Sana,90,90,98,90,90,458,91.6,A+,A+

#### Outline Function

In [52]:
def Calculate_Grade(per):
    if per>=90:
        return "A+"
    elif per>=80:
        return "A"
    elif per>=70:
        return "B"
    elif per>=60:
        return 'C'
    elif per>=50:
        return "D"
    else:
        return "F"

In [53]:
result['Grade5']=result.Percentage.apply(Calculate_Grade)
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade3,Grade4,Grade5
0,11,Usman,75,87,89,87,75,413,82.6,A,A,A
1,12,Rehana,67,78,67,78,67,357,71.4,B,B,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A,A,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A,A,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B,B,B
5,16,Hashir,98,73,56,73,98,398,79.6,B,B,B
6,17,Maryam,87,94,54,94,87,416,83.2,A,A,A
7,18,Asim,76,85,56,85,76,378,75.6,B,B,B
8,19,Rehan,45,78,78,78,45,324,64.8,C,C,C
9,20,Sana,90,90,98,90,90,458,91.6,A+,A+,A+

In [54]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade3,Grade4,Grade5
0,11,Usman,75,87,89,87,75,413,82.6,A,A,A
1,12,Rehana,67,78,67,78,67,357,71.4,B,B,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A,A,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A,A,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B,B,B
5,16,Hashir,98,73,56,73,98,398,79.6,B,B,B
6,17,Maryam,87,94,54,94,87,416,83.2,A,A,A
7,18,Asim,76,85,56,85,76,378,75.6,B,B,B
8,19,Rehan,45,78,78,78,45,324,64.8,C,C,C
9,20,Sana,90,90,98,90,90,458,91.6,A+,A+,A+

In [55]:
del result['Grade3']
del result['Grade4']

In [56]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
0,11,Usman,75,87,89,87,75,413,82.6,A
1,12,Rehana,67,78,67,78,67,357,71.4,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B
5,16,Hashir,98,73,56,73,98,398,79.6,B
6,17,Maryam,87,94,54,94,87,416,83.2,A
7,18,Asim,76,85,56,85,76,378,75.6,B
8,19,Rehan,45,78,78,78,45,324,64.8,C
9,20,Sana,90,90,98,90,90,458,91.6,A+

# Accessing Columns
 - Single
 - Multiple Columns

In [57]:
result['Total']

0    413
1    357
2    441
3    436
4    380
5    398
6    416
7    378
8    324
9    458
Name: Total, dtype: int64

In [58]:
result.Total

0    413
1    357
2    441
3    436
4    380
5    398
6    416
7    378
8    324
9    458
Name: Total, dtype: int64

In [59]:
result[['Name', 'Grade5']]

      Name Grade5
0    Usman      A
1   Rehana      B
2  Ghaffar      A
3    Nawaz      A
4   Bilwal      B
5   Hashir      B
6   Maryam      A
7     Asim      B
8    Rehan      C
9     Sana     A+

In [60]:
result.Name.size

10

In [61]:
result.Total.max()

458

In [62]:
result.Total.mean()

np.float64(400.1)

##### Unique
    - nunique()
    - unique()

In [63]:
result.Grade5.nunique()

4

In [64]:
result.Grade5.unique()

array(['A', 'B', 'C', 'A+'], dtype=object)

In [65]:
result.Grade5.value_counts()

Grade5
A     4
B     4
C     1
A+    1
Name: count, dtype: int64

# Accessing Row/Rows

result[Rows,Columns]
result[start_row:end_row:step , start_col: end_col]

In [66]:
result[4,'DeepLearning'] # error

KeyError: (4, 'DeepLearning')

In [ ]:
result[4,6] # error

In [ ]:
result.iloc[4,6] # ok

In [ ]:
result.loc[4,'DeepLearning'] # ok

In [ ]:
result.index

In [ ]:
result.columns

In [67]:
result.loc[2:6, ['Total', 'Percentage', 'Grade5']]

   Total  Percentage Grade5
2    441        88.2      A
3    436        87.2      A
4    380        76.0      B
5    398        79.6      B
6    416        83.2      A

In [68]:
result.loc[::2, ['Total', 'Percentage', 'Grade5']]

   Total  Percentage Grade5
0    413        82.6      A
2    441        88.2      A
4    380        76.0      B
6    416        83.2      A
8    324        64.8      C

In [69]:
result.loc[::2, ::2]

   Roll  Python  Statistics  DeepLearning  Percentage
0    11      75          89            75        82.6
2    13      78          89            78        88.2
4    15      90          78            90        76.0
6    17      87          54            87        83.2
8    19      45          78            45        64.8

In [70]:
result.loc[[3,6,9], ['Roll', 'Grade5', 'Python']]

   Roll Grade5  Python
3    14      A      89
6    17      A      87
9    20     A+      90

In [71]:
result.loc[3:5,'Pandas':'DeepLearning' ]

   Pandas  Statistics  MachineLearning  DeepLearning
3      91          76               91            89
4      61          78               61            90
5      73          56               73            98

# Querry Filters

In [72]:
result

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
0,11,Usman,75,87,89,87,75,413,82.6,A
1,12,Rehana,67,78,67,78,67,357,71.4,B
2,13,Ghaffar,78,98,89,98,78,441,88.2,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B
5,16,Hashir,98,73,56,73,98,398,79.6,B
6,17,Maryam,87,94,54,94,87,416,83.2,A
7,18,Asim,76,85,56,85,76,378,75.6,B
8,19,Rehan,45,78,78,78,45,324,64.8,C
9,20,Sana,90,90,98,90,90,458,91.6,A+

In [73]:
# Fetch all students having Stats marks less than 80.
result[result.Statistics<80]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
1,12,Rehana,67,78,67,78,67,357,71.4,B
3,14,Nawaz,89,91,76,91,89,436,87.2,A
4,15,Bilwal,90,61,78,61,90,380,76.0,B
5,16,Hashir,98,73,56,73,98,398,79.6,B
6,17,Maryam,87,94,54,94,87,416,83.2,A
7,18,Asim,76,85,56,85,76,378,75.6,B
8,19,Rehan,45,78,78,78,45,324,64.8,C

In [74]:
result[(result.Name.str[0]=='A') | (result.Name.str[0]=='E') | (result.Name.str[0]=='I') | (result.Name.str[0]=='O') | (result.Name.str[0]=='U')]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
0,11,Usman,75,87,89,87,75,413,82.6,A
7,18,Asim,76,85,56,85,76,378,75.6,B

In [75]:
result.sort_values(ascending=False, by='Percentage',axis=0)

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
9,20,Sana,90,90,98,90,90,458,91.6,A+
2,13,Ghaffar,78,98,89,98,78,441,88.2,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A
6,17,Maryam,87,94,54,94,87,416,83.2,A
0,11,Usman,75,87,89,87,75,413,82.6,A
5,16,Hashir,98,73,56,73,98,398,79.6,B
4,15,Bilwal,90,61,78,61,90,380,76.0,B
7,18,Asim,76,85,56,85,76,378,75.6,B
1,12,Rehana,67,78,67,78,67,357,71.4,B
8,19,Rehan,45,78,78,78,45,324,64.8,C

In [76]:
# students having grade A and mark in Pandas greater than 90.
result[(result.Grade5=='A') & (result.Pandas>90)]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
2,13,Ghaffar,78,98,89,98,78,441,88.2,A
3,14,Nawaz,89,91,76,91,89,436,87.2,A
6,17,Maryam,87,94,54,94,87,416,83.2,A

In [77]:
# Student that has max marks in ML.
result.MachineLearning.max()

98

In [79]:
result[result.MachineLearning==result.MachineLearning.max()]

,Roll,Name,Python,Pandas,Statistics,MachineLearning,DeepLearning,Total,Percentage,Grade5
2,13,Ghaffar,78,98,89,98,78,441,88.2,A

In [80]:
df = pd.read_csv('ai_student_impact_dataset.csv')

In [81]:
df.shape

(50000, 16)

In [86]:
df.head(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
5,100006,STEM,Junior,3.449,6.50,Debugging/Troubleshooting,Beginner,1,False,14.19,4,Allowed_With_Citation,5,3.666,65.92,High
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
7,100008,Arts,Junior,2.746,5.33,Copywriting/Drafting,Intermediate,3,False,18.45,2,Actively_Encouraged,1,2.965,85.09,Medium
8,100009,Business,Sophomore,3.420,2.00,Debugging/Troubleshooting,Beginner,2,True,2.87,1,Strict_Ban,5,3.396,55.71,Medium
9,100010,Business,Sophomore,3.046,19.99,Debugging/Troubleshooting,Intermediate,2,True,12.49,3,Strict_Ban,8,2.978,87.18,High

In [85]:
df.tail(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49991,149992,Humanities,Freshman,2.708,13.34,Copywriting/Drafting,Intermediate,2,False,11.65,4,Allowed_With_Citation,5,2.785,65.24,High
49992,149993,Business,Graduate,2.829,2.59,Debugging/Troubleshooting,Advanced,3,True,7.54,1,Allowed_With_Citation,4,3.176,84.04,Low
49993,149994,STEM,Sophomore,3.588,25.64,Debugging/Troubleshooting,Intermediate,3,True,4.62,5,Strict_Ban,10,3.841,58.44,High
49994,149995,Humanities,Senior,3.556,15.19,Summarizing_Reading,Advanced,4,True,1.00,3,Actively_Encouraged,5,3.788,74.76,High
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [84]:
df.sample(10)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
33709,133710,Medical,Junior,2.373,5.20,Direct_Answer_Generation,Beginner,1,True,6.53,2,Allowed_With_Citation,4,2.519,66.47,Medium
30963,130964,STEM,Junior,2.871,8.29,Summarizing_Reading,Advanced,3,True,1.00,5,Allowed_With_Citation,4,2.979,69.20,Medium
6807,106808,Humanities,Graduate,2.548,8.85,Summarizing_Reading,Beginner,3,False,10.81,4,Allowed_With_Citation,3,2.753,88.86,High
34949,134950,Business,Freshman,3.359,32.16,Debugging/Troubleshooting,Intermediate,1,True,1.00,8,Allowed_With_Citation,4,3.048,66.13,High
9095,109096,Medical,Graduate,3.690,5.63,Ideation,Beginner,2,True,16.95,2,Actively_Encouraged,3,4.000,85.56,Medium
43343,143344,Business,Sophomore,2.058,23.50,Copywriting/Drafting,Beginner,2,True,1.00,7,Strict_Ban,10,2.014,53.83,High
42965,142966,Humanities,Freshman,3.541,6.50,Debugging/Troubleshooting,Advanced,3,True,7.36,4,Allowed_With_Citation,8,4.000,75.11,Medium
11894,111895,Humanities,Junior,3.202,0.07,Copywriting/Drafting,Intermediate,1,False,17.77,1,Allowed_With_Citation,3,3.532,71.72,Medium
19687,119688,Humanities,Freshman,3.460,0.24,Summarizing_Reading,Beginner,1,False,18.57,4,Strict_Ban,7,3.708,64.84,Medium
12211,112212,Business,Sophomore,3.248,1.01,Ideation,Intermediate,3,False,10.20,2,Actively_Encouraged,3,3.405,89.49,Low

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [88]:
df.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')

In [90]:
df.Major_Category.nunique()

5

In [91]:
df.Major_Category.value_counts()

Major_Category
STEM          15059
Business      12538
Humanities     9994
Medical        6476
Arts           5933
Name: count, dtype: int64

In [93]:
df.Year_of_Study.value_counts()

Year_of_Study
Junior       11045
Freshman     11031
Senior       10634
Sophomore     9860
Graduate      7430
Name: count, dtype: int64

In [95]:
df.Pre_Semester_GPA.mean()

np.float64(3.14610234)

In [98]:
df[df.Major_Category=='STEM']['Pre_Semester_GPA'].mean()

np.float64(3.14585184939239)

In [99]:
df[df.Major_Category=='Business']['Pre_Semester_GPA'].mean()

np.float64(3.1417598500558297)

In [100]:
df[df.Major_Category=='Humanities']['Pre_Semester_GPA'].mean()

np.float64(3.1478495097058237)

In [101]:
df[df.Major_Category=='Medical']['Pre_Semester_GPA'].mean()

np.float64(3.151769302038295)

In [103]:
df[df.Major_Category=='Arts']['Pre_Semester_GPA'].mean()

np.float64(3.1467862801280972)

In [156]:
emp = pd.read_excel("employee.xlsx",index_col='Serial')
emp

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
13        2156    Engineer  Production  45.0   89000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN
17        2156    Engineer  Production  45.0   89000.0
18        2123  Office Boy    Accounts  27.0   45000.0
19        1005     Manager          HR  45.0  120000.0
20        2123  Office Boy    Accounts  27.0   45000.0
21        6543     Officer  Production  29.0  100000.0
22        3214  Accountant     Account  49.0  123000.0
23        2156    Engineer  Production  45.0   89000.0
24        1098     Officer          IT  25.0  100000.0
25        2156    Engineer  Production  45.0   89000.0
26        2123  Office Boy    Accounts  27.0   45000.0

In [157]:
emp.head()

        Emp_ID Designation Department   Age    Salary
Serial
1         1101     Manager   Accounts  50.0  200000.0
2         1107     Officer         IT  30.0   80000.0
3         1203     Officer         HR  28.0       NaN
4         1005     Manager         HR  45.0  120000.0
5         2123  Office Boy   Accounts  27.0   45000.0

In [158]:
# What is the average salary of managers.
# What is the maximum salary in IT department
# What is the average salary of Accounts depart.
# the most aged emp in the organization
# What the Designation of the youngest emp

In [159]:
# What is the average salary of managers.
emp[emp.Designation=='Manager']['Salary'].mean()

np.float64(146666.66666666666)

In [160]:
# What is the maximum salary in IT department
emp[emp.Department=='IT']['Salary'].max()

100000.0

In [161]:
# the most aged person in the organization
emp[emp.Age==emp.Age.max()]

        Emp_ID Designation Department   Age    Salary
Serial
1         1101     Manager   Accounts  50.0  200000.0

In [162]:
# What the Designation of the youngest emp
emp[emp.Age==emp.Age.min()]['Designation']

Serial
9    Manager
Name: Designation, dtype: object

# Data Cleaning
    - Data Type Issues 
    - Missing Values
    - Duplicate Values
    - Outlier Values
    - Misc issues

In [163]:
emp.isna().sum()

Emp_ID         0
Designation    0
Department     2
Age            1
Salary         3
dtype: int64

In [164]:
emp.duplicated().sum()

np.int64(11)

In [165]:
emp.duplicated(subset=['Designation', 'Department']).sum()

np.int64(14)

In [167]:
emp.drop_duplicates(subset=['Designation','Department','Age','Salary'],inplace=True)

In [168]:
emp

        Emp_ID Designation  Department   Age    Salary
Serial
1         1101     Manager    Accounts  50.0  200000.0
2         1107     Officer          IT  30.0   80000.0
3         1203     Officer          HR  28.0       NaN
4         1005     Manager          HR  45.0  120000.0
5         2123  Office Boy    Accounts  27.0   45000.0
6         2451  Accountant         NaN  34.0  100000.0
7         1111  Accountant    Accounts   NaN  110000.0
8         1001     Officer          IT  25.0   75000.0
9         1234     Manager          IT  23.0       NaN
10        2156    Engineer  Production  45.0   89000.0
11        6543     Officer  Production  29.0  100000.0
12        3214  Accountant     Account  49.0  123000.0
14        1098     Officer          IT  25.0  100000.0
15        2912     Officer          IT  31.0   90000.0
16        1222     Officer         NaN  25.0       NaN