# Pandas:
   Python library for data analysis
# Pandas Data Structure 
    - Pandas Series 
    - Pandas DataFrame

#### Pandas Series:
      Data in 1D is series. 
      Data with Only Singlle Column

In [2]:
import pandas as pd

In [3]:
s1 = pd.Series(['Apples','Oranges','Mangoes','Cherries'])
s1

0      Apples
1     Oranges
2     Mangoes
3    Cherries
dtype: object

Components: 
    Values : we provoided values
    Index  : It uses default indices
    Dtype  : since all values are strings (objects)
    Name   : Name of the series

In [4]:
s1 = pd.Series(['Apples','Oranges','Mangoes','Cherries'], index=[12,24,12,36], name='fruits')
s1

12      Apples
24     Oranges
12     Mangoes
36    Cherries
Name: fruits, dtype: object

In [5]:
s2 = pd.Series(data=[12,24,12,36,24,12,48,60],index=['Apples','Oranges','Mangoes','Cherries','Bananas','Gauva','Lemon','Kiwi'])

In [7]:
# indices can be string indices
s2

Apples      12
Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
Lemon       48
Kiwi        60
dtype: int64

In [8]:
# Note: when providing string indices still we can refer to default inrt indices

In [9]:
s2['Lemon']

np.int64(48)

In [6]:
s2['Mangoes']

np.int64(12)

In [11]:
s1[24]

'Oranges'

In [12]:
# using default indices over string indices
s2

Apples      12
Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
Lemon       48
Kiwi        60
dtype: int64

In [13]:
s2.iloc[4]

np.int64(24)

In [14]:
s2.loc['Gauva']

np.int64(12)

# Slice a Series

In [15]:
s1

12      Apples
24     Oranges
12     Mangoes
36    Cherries
Name: fruits, dtype: object

In [16]:
s1.iloc[0:3] # int index dont include last index in slice

12     Apples
24    Oranges
12    Mangoes
Name: fruits, dtype: object

In [17]:
s2['Oranges':'Gauva'] # where string index include last one also.

Oranges     24
Mangoes     12
Cherries    36
Bananas     24
Gauva       12
dtype: int64

# DataFrame:
   - Data with more than one columns.
   - 2D data

In [7]:
result = {'Roll':[11,12,13,14,15,16,17,18,19, 20],
          'Name':['Usman','Rehana','Ghaffar','Nawaz','Bilwal','Hashir', 'Maryam','Asim','Rehan','Sana'],
          'Python':[75,67,78,89,90,98,87,76,45,90],
          'Pandas':[87,78,98,91,61,73,94,85,78,90], 
          'Statistics':[89,67,89,76,78,56,54,56,78,98],
          'MachineLearning':[87,78,98,91,61,73,94,85,78,90],'DeepLearning':[75,67,78,89,90,98,87,76,45,90]}
result

{'Roll': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 'Name': ['Usman',
  'Rehana',
  'Ghaffar',
  'Nawaz',
  'Bilwal',
  'Hashir',
  'Maryam',
  'Asim',
  'Rehan',
  'Sana'],
 'Python': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90],
 'Pandas': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'Statistics': [89, 67, 89, 76, 78, 56, 54, 56, 78, 98],
 'MachineLearning': [87, 78, 98, 91, 61, 73, 94, 85, 78, 90],
 'DeepLearning': [75, 67, 78, 89, 90, 98, 87, 76, 45, 90]}

In [16]:
result.iloc[2]

Roll                    13
Name               Ghaffar
Python                  78
Pandas                  98
Statistics              89
MachineLearning         98
DeepLearning            78
Name: 2, dtype: object

In [17]:
result = pd.DataFrame(result)
result

   Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90

In [8]:
result = pd.DataFrame(result)
result

   Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90

In [12]:
result.value_counts

<bound method DataFrame.value_counts of    Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90>

In [13]:
result.columns

Index(['Roll', 'Name', 'Python', 'Pandas', 'Statistics', 'MachineLearning',
       'DeepLearning'],
      dtype='object')

In [18]:
result.iloc[4, 5]

np.int64(61)

In [15]:
result.index

RangeIndex(start=0, stop=10, step=1)

#### Working with Columns
   - Adding more columns to df
           - passing hard coded value
           - generate data from data
                 
   - Del columns from df
   - Access single column (series)
   - Access multiple columns (2d)

In [ ]:
result['Total']= result.Python + result.Pandas + result.MachineLearning + result.Statistics + result.DeepLearning
result

In [ ]:
result['Percentage'] = result.Total/500*100
result

##### List Comprenshion

In [ ]:
result['Grade3'] = ["A+" if per>=90 
                    else "A" if per>=80 
                    else "B" if per>=70 
                    else "C" if per>=60 
                    else "D" if per>=50 else "F"   
                                for per in result.Percentage]
result

#### lambda function are anonymous function / Inline Function

In [24]:
result['Grade4'] = result.Percentage.apply(lambda per:"A+" if per>=90 else "A" if per>=80 else "B" if per>=70 else "C" if per>=60 else "D" if per>=50 else"F")

In [1]:
result

NameError: name 'result' is not defined

#### Outline Function

In [26]:
def Calculate_Grade(per):
    if per>=90:
        return "A+"
    elif per>=80:
        return "A"
    elif per>=70:
        return "B"
    elif per>=60:
        return 'C'
    elif per>=50:
        return "D"
    else:
        return "F"

In [26]:
result['Grade5']=result.Percentage.apply(Calculate_Grade)
result

AttributeError: 'DataFrame' object has no attribute 'Percentage'

In [25]:
# del result['Grade1']
# del result['Grade2']
# del result['Grade3']
# del result['Grade4']

In [24]:
result

   Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90

In [19]:
result

   Roll     Name  Python  Pandas  Statistics  MachineLearning  DeepLearning
0    11    Usman      75      87          89               87            75
1    12   Rehana      67      78          67               78            67
2    13  Ghaffar      78      98          89               98            78
3    14    Nawaz      89      91          76               91            89
4    15   Bilwal      90      61          78               61            90
5    16   Hashir      98      73          56               73            98
6    17   Maryam      87      94          54               94            87
7    18     Asim      76      85          56               85            76
8    19    Rehan      45      78          78               78            45
9    20     Sana      90      90          98               90            90

In [21]:
result(result.Statistics<80)

TypeError: 'DataFrame' object is not callable

In [ ]:
# result.Name.str.

In [ ]:
result.Grade5

In [28]:
highest_student = result.loc[result['MachineLearning'].idxmax(), 'Name']

print(highest_student)

Ghaffar