In [139]:
import pandas as pd
import matplotlib.pyplot as plt

## Techniques i will be used in this project inshallah,
- Summary Statistics
- Distribution Plot
- Info (Data Type/Non-Null Count)
- Visual Inspect.

In [140]:
df1 = pd.read_csv('loan-train.csv')
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1609,LP009965,Male,No,3+,Graduate,Yes,13658,9822.0,323.0,180.0,0.0,Urban,N
1610,LP009966,Male,Yes,0,Graduate,No,13683,2223.0,182.0,360.0,1.0,Semiurban,Y
1611,LP009970,Male,Yes,3+,Not Graduate,Yes,19409,768.0,222.0,360.0,0.0,Urban,N
1612,LP009977,Female,Yes,2,Graduate,Yes,8997,1354.0,355.0,360.0,0.0,Rural,Y
1613,LP009996,Female,Yes,2,Graduate,No,19858,6305.0,463.0,240.0,1.0,Rural,Y

In [141]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1614 entries, 0 to 1613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            1614 non-null   object
 1   Gender             1601 non-null   object
 2   Married            1611 non-null   object
 3   Dependents         1599 non-null   object
 4   Education          1614 non-null   object
 5   Self_Employed      1582 non-null   object
 6   ApplicantIncome    1614 non-null   int64
 7   CoapplicantIncome  1614 non-null   float64
 8   LoanAmount         1592 non-null   float64
 9   Loan_Amount_Term   1600 non-null   float64
 10  Credit_History     1564 non-null   float64
 11  Property_Area      1614 non-null   object
 12  Loan_Status        1614 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 164.1+ KB

In [142]:
df1.describe().round()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,1614.0,1614.0,1592.0,1600.0,1564.0
mean,8746.0,3659.0,219.0,290.0,1.0
std,6250.0,3292.0,134.0,82.0,0.0
min,150.0,0.0,9.0,12.0,0.0
25%,3675.0,986.0,112.0,240.0,0.0
50%,7045.0,2942.0,180.0,360.0,1.0
75%,13251.0,5893.0,324.0,360.0,1.0
max,81000.0,41667.0,700.0,480.0,1.0

In [143]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [144]:
df1['Gender'].value_counts()

Gender
Male      980
Female    621
Name: count, dtype: int64

In [145]:
df1.shape

(1614, 13)

In [146]:
# check kar raha hun k kitna percentence data missing ha

df1.isnull().sum()/len(df1)*100

Loan_ID              0.000000
Gender               0.805452
Married              0.185874
Dependents           0.929368
Education            0.000000
Self_Employed        1.982652
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           1.363073
Loan_Amount_Term     0.867410
Credit_History       3.097893
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

In [147]:
# df1.dropna().shape

In [149]:
df1.isna().shape

(1614, 13)

In [150]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [151]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1614 entries, 0 to 1613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            1614 non-null   object
 1   Gender             1601 non-null   object
 2   Married            1611 non-null   object
 3   Dependents         1599 non-null   object
 4   Education          1614 non-null   object
 5   Self_Employed      1582 non-null   object
 6   ApplicantIncome    1614 non-null   int64
 7   CoapplicantIncome  1614 non-null   float64
 8   LoanAmount         1592 non-null   float64
 9   Loan_Amount_Term   1600 non-null   float64
 10  Credit_History     1564 non-null   float64
 11  Property_Area      1614 non-null   object
 12  Loan_Status        1614 non-null   object
dtypes: float64(4), int64(1), object(8)
memory usage: 164.1+ KB

In [152]:
df1.shape

(1614, 13)

In [153]:
df1['Loan_ID'].value_counts().head(10)

Loan_ID
LP006706    3
LP006444    2
LP003618    2
LP003763    2
LP005791    2
LP009226    2
LP006497    2
LP008688    2
LP008089    2
LP008681    2
Name: count, dtype: int64

In [154]:
df1[df1['Loan_ID'] == 'LP008089']

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1346,LP008089,Male,Yes,2,Graduate,Yes,13245,9390.0,232.0,240.0,0.0,Semiurban,N
1347,LP008089,Male,Yes,1,Graduate,Yes,6679,6604.0,468.0,240.0,1.0,Urban,N

In [155]:
# df1['Real_ID'] = 'LP' + df1.index.astype(str).str.zfill(6)

In [156]:
df1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1609,LP009965,Male,No,3+,Graduate,Yes,13658,9822.0,323.0,180.0,0.0,Urban,N
1610,LP009966,Male,Yes,0,Graduate,No,13683,2223.0,182.0,360.0,1.0,Semiurban,Y
1611,LP009970,Male,Yes,3+,Not Graduate,Yes,19409,768.0,222.0,360.0,0.0,Urban,N
1612,LP009977,Female,Yes,2,Graduate,Yes,8997,1354.0,355.0,360.0,0.0,Rural,Y
1613,LP009996,Female,Yes,2,Graduate,No,19858,6305.0,463.0,240.0,1.0,Rural,Y

In [157]:
# df1 = df1.drop(columns=['Loan_ID'])

In [158]:
for col in df1.columns:
    if df1[col].nunique()<20:
        # print(col)
        print(df1[col].value_counts())
        print("-"*50)

Gender
Male      980
Female    621
Name: count, dtype: int64
--------------------------------------------------
Married
Yes    925
No     686
Name: count, dtype: int64
--------------------------------------------------
Dependents
0     619
1     341
2     336
3+    303
Name: count, dtype: int64
--------------------------------------------------
Education
Graduate        952
Not Graduate    662
Name: count, dtype: int64
--------------------------------------------------
Self_Employed
No     999
Yes    583
Name: count, dtype: int64
--------------------------------------------------
Loan_Amount_Term
360.0    845
180.0    384
240.0    331
480.0     15
300.0     13
84.0       4
120.0      3
60.0       2
36.0       2
12.0       1
Name: count, dtype: int64
--------------------------------------------------
Credit_History
1.0    994
0.0    570
Name: count, dtype: int64
--------------------------------------------------
Property_Area
Urban        549
Semiurban    545
Rural        520
Name: count, dtype: int64
--------------------------------------------------
Loan_Status
Y    915
N    699
Name: count, dtype: int64
--------------------------------------------------

# Handling Missing Data

In [159]:
# df1.dropna(subset=['Gender'], inplace=True )

In [160]:
df1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [164]:
import re
df1['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [166]:
df1['Dependents']

0        0
1        1
2        0
3        0
4        0
        ..
1609    3+
1610     0
1611    3+
1612     2
1613     2
Name: Dependents, Length: 1614, dtype: object