In [1]:
import pandas as pd

In [4]:
emp = pd.read_excel("employee.xlsx")

In [16]:
emp = pd.DataFrame(emp)
emp[emp.Designation=="Manager"]["Salary"].mean()

np.float64(146666.66666666666)

In [ ]:
# 200000.0+120000.0+120000.0/SUM OF ALL

350000.0

In [ ]:
# emp[emp.Age==]

Empty DataFrame
Columns: [Serial, Emp_ID, Designation, Department, Age, Salary]
Index: []

In [20]:
emp[emp.Age == emp.Age.max()]

   Serial  Emp_ID Designation Department   Age    Salary
0       1    1101     Manager   Accounts  50.0  200000.0

In [22]:
emp[emp.Age == emp.Age.min()]

   Serial  Emp_ID Designation Department   Age  Salary
8       9    1234     Manager         IT  23.0     NaN

In [29]:
emp[(emp.Designation == "Officer" )& (emp.Age == 25)]

    Serial  Emp_ID Designation Department   Age    Salary
7        8    1001     Officer         IT  25.0   75000.0
13      14    1098     Officer         IT  25.0  100000.0
15      16    1222     Officer        NaN  25.0       NaN
23      24    1098     Officer         IT  25.0  100000.0

In [25]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    1005     Manager          HR  45.0  120000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0
20      21    6543     Officer  Production  29.0  100000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0

Data Cleaning

In [31]:
emp.isna()

    Serial  Emp_ID  Designation  Department    Age  Salary
0    False   False        False       False  False   False
1    False   False        False       False  False   False
2    False   False        False       False  False    True
3    False   False        False       False  False   False
4    False   False        False       False  False   False
5    False   False        False        True  False   False
6    False   False        False       False   True   False
7    False   False        False       False  False   False
8    False   False        False       False  False    True
9    False   False        False       False  False   False
10   False   False        False       False  False   False
11   False   False        False       False  False   False
12   False   False        False       False  False   False
13   False   False        False       False  False   False
14   False   False        False       False  False   False
15   False   False        False        True  False    True
16   False   False        False       False  False   False
17   False   False        False       False  False   False
18   False   False        False       False  False   False
19   False   False        False       False  False   False
20   False   False        False       False  False   False
21   False   False        False       False  False   False
22   False   False        False       False  False   False
23   False   False        False       False  False   False
24   False   False        False       False  False   False
25   False   False        False       False  False   False

In [32]:
emp.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
dtype: bool

In [37]:
emp.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
dtype: bool

In [40]:
emp = pd.read_excel("employee.xlsx")

In [41]:
emp

    Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    1005     Manager          HR  45.0  120000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0
20      21    6543     Officer  Production  29.0  100000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0

In [42]:
emp.isna()

    Serial  Emp_ID  Designation  Department    Age  Salary
0    False   False        False       False  False   False
1    False   False        False       False  False   False
2    False   False        False       False  False    True
3    False   False        False       False  False   False
4    False   False        False       False  False   False
5    False   False        False        True  False   False
6    False   False        False       False   True   False
7    False   False        False       False  False   False
8    False   False        False       False  False    True
9    False   False        False       False  False   False
10   False   False        False       False  False   False
11   False   False        False       False  False   False
12   False   False        False       False  False   False
13   False   False        False       False  False   False
14   False   False        False       False  False   False
15   False   False        False        True  False    True
16   False   False        False       False  False   False
17   False   False        False       False  False   False
18   False   False        False       False  False   False
19   False   False        False       False  False   False
20   False   False        False       False  False   False
21   False   False        False       False  False   False
22   False   False        False       False  False   False
23   False   False        False       False  False   False
24   False   False        False       False  False   False
25   False   False        False       False  False   False

In [43]:
emp.duplicated().sum()

np.int64(0)

In [46]:
emp.duplicated

<bound method DataFrame.duplicated of     Serial  Emp_ID Designation  Department   Age    Salary
0        1    1101     Manager    Accounts  50.0  200000.0
1        2    1107     Officer          IT  30.0   80000.0
2        3    1203     Officer          HR  28.0       NaN
3        4    1005     Manager          HR  45.0  120000.0
4        5    2123  Office Boy    Accounts  27.0   45000.0
5        6    2451  Accountant         NaN  34.0  100000.0
6        7    1111  Accountant    Accounts   NaN  110000.0
7        8    1001     Officer          IT  25.0   75000.0
8        9    1234     Manager          IT  23.0       NaN
9       10    2156    Engineer  Production  45.0   89000.0
10      11    6543     Officer  Production  29.0  100000.0
11      12    3214  Accountant     Account  49.0  123000.0
12      13    2156    Engineer  Production  45.0   89000.0
13      14    1098     Officer          IT  25.0  100000.0
14      15    2912     Officer          IT  31.0   90000.0
15      16    1222     Officer         NaN  25.0       NaN
16      17    2156    Engineer  Production  45.0   89000.0
17      18    2123  Office Boy    Accounts  27.0   45000.0
18      19    1005     Manager          HR  45.0  120000.0
19      20    2123  Office Boy    Accounts  27.0   45000.0
20      21    6543     Officer  Production  29.0  100000.0
21      22    3214  Accountant     Account  49.0  123000.0
22      23    2156    Engineer  Production  45.0   89000.0
23      24    1098     Officer          IT  25.0  100000.0
24      25    2156    Engineer  Production  45.0   89000.0
25      26    2123  Office Boy    Accounts  27.0   45000.0>